name: Deploy to AWS S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main # Adjust to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload file to S3
        run: |
          echo "Current directory content:"
          ls -al
          echo "Bucket Name: ${{ secrets.S3_BUCKET_NAME }}"
          echo "Uploading script.js to S3:"
          aws s3 cp ./script.js s3://${{ secrets.S3_BUCKET_NAME }}/script.js

      - name: Invalidate CloudFront cache
        run: |
          echo "Invalidating script.js in CloudFront"
          echo "Distribution ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}"
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/script.js"
